# Generated by Django 4.0.5 on 2022-06-02 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_alter_bloguser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
