# Generated by Django 4.0.5 on 2022-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_bloguser_interests_bloguser_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_creating',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
