# Generated by Django 4.0.5 on 2022-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_date_of_creating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='blog_user',
        ),
    ]
