# Generated by Django 4.0.5 on 2022-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_rename_user_post_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_user',
            new_name='user',
        ),
    ]
