# Generated by Django 4.0.5 on 2022-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_rename_blog_user_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='user',
        ),
    ]
